'use client';
import { useEffect, useState } from 'react';
const sections=[['overview','نمای کلی'],['products','محصولات'],['categories','دسته‌بندی‌ها'],['slides','اسلایدر'],['content','متن‌ها و تماس'],['media','کتابخانه تصاویر'],['password','تغییر رمز']];
const blankProduct={slug:'',sku:'',nameFa:'',nameEn:'',descriptionFa:'',descriptionEn:'',specsFa:'',specsEn:'',images:[],categoryId:null,status:'DRAFT'};
const blankSlide={titleFa:'',titleEn:'',captionFa:'',captionEn:'',image:'',href:'/products',position:0,active:false};
const blankCategory={slug:'',nameFa:'',nameEn:''};
const statusLabels={DRAFT:'پیش‌نویس',PUBLISHED:'منتشرشده',ARCHIVED:'بایگانی'};
const contentFields=[['title','عنوان صفحه در مرورگر',false,180],['aboutTitle','عنوان درباره ما',true,160],['belief','متن معرفی شرکت',true,4000],['directorLabel','عنوان پیام مدیرعامل',false,120],['directorMessage','پیام مدیرعامل',true,8000],['contactTitle','عنوان تماس',false,180],['contactText','توضیح تماس',true,2000],['address','آدرس',true,700]];
async function request(path,options={}){
 const isForm=options.body instanceof FormData;
 const response=await fetch(`/api/${path}`,{...options,headers:{...(!isForm&&options.body?{'Content-Type':'application/json'}:{}),...options.headers},body:isForm?options.body:options.body?JSON.stringify(options.body):undefined,cache:'no-store'});
 const body=await response.json().catch(()=>({}));
 if(!response.ok){const error=new Error(response.status===429?'تعداد تلاش‌ها زیاد است؛ یک دقیقه صبر کنید.':body.message||'ارتباط با سرور انجام نشد.');error.status=response.status;error.fields=body.fields;throw error;}return body;
}
function Field({label,value,onChange,multiline=false,dir,required=false,maxLength=12000,type='text',hint}){
 return <label className="admin-field"><span>{label}{required&&<small> *</small>}</span>{multiline?<textarea dir={dir} value={value??''} onChange={e=>onChange(e.target.value)} rows={4} maxLength={maxLength} required={required}/>:<input dir={dir} type={type} value={value??''} onChange={e=>onChange(e.target.value)} maxLength={maxLength} required={required}/>} {hint&&<small className="field-hint">{hint}</small>}</label>;
}
function ImagePicker({images,onChange,media,onUpload,busy,multiple=false}){
 return <div className="image-picker"><div className="admin-image-list">{images.filter(Boolean).map((src,i)=><div key={`${src}-${i}`}><img src={src} alt={`تصویر ${i+1}`}/><div><button type="button" className="text-button" onClick={()=>onChange(images.filter((_,index)=>index!==i))}>حذف از این مورد</button>{multiple&&i>0&&<button type="button" className="text-button" onClick={()=>{const list=[...images];[list[i-1],list[i]]=[list[i],list[i-1]];onChange(list);}}>جلوتر ↑</button>}</div></div>)}</div>
 <label className="upload-button">{busy?'در حال بارگذاری…':'بارگذاری تصویر جدید'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||multiple&&images.length>=8} onChange={async e=>{const file=e.target.files?.[0];if(file){const item=await onUpload(file);if(item)onChange(multiple?[...images,item.url]:[item.url]);}e.target.value='';}}/></label><small>JPG، PNG یا WebP · حداکثر ۸ مگابایت{multiple?' · تا ۸ تصویر؛ اولی تصویر اصلی است.':''}</small>
 {media.length>0&&<label className="admin-field"><span>یا انتخاب از تصاویر قبلی</span><select value="" disabled={multiple&&images.length>=8} onChange={e=>{if(!e.target.value)return;onChange(multiple?[...new Set([...images,e.target.value])]:[e.target.value]);}}><option value="">انتخاب تصویر…</option>{media.map(m=><option key={m.id} value={m.url}>{m.name||m.url}</option>)}</select></label>}</div>;
}
export default function Admin(){
 const [user,setUser]=useState(null),[ready,setReady]=useState(false),[section,setSection]=useState('overview');
 const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[slides,setSlides]=useState([]),[content,setContent]=useState(null),[media,setMedia]=useState([]);
 const [editing,setEditing]=useState(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[notice,setNotice]=useState(null),[filter,setFilter]=useState(''),[dataReady,setDataReady]=useState(false);
 const [credentials,setCredentials]=useState({username:'',password:''}),[passwords,setPasswords]=useState({currentPassword:'',newPassword:'',confirm:''});
 const report=e=>{setNotice({error:true,text:e.message+(e.fields?.length?' '+e.fields.map(f=>`${f.field}: ${f.message}`).join('؛ '):'')});if(e.status===401){setUser(null);setDataReady(false);}};
 const load=async()=>{setDataReady(false);try{const [p,c,s,t,m]=await Promise.all(['products','categories','slides','content','media'].map(key=>request(`admin/${key}`)));setProducts(p);setCategories(c);setSlides(s);setContent(t);setMedia(m);setDataReady(true);}catch(e){report(e);}};
 useEffect(()=>{request('auth/me').then(setUser).catch(e=>{if(e.status!==401)report(e);}).finally(()=>setReady(true));},[]);
 useEffect(()=>{if(user&&!user.mustChangePassword)load();},[user?.id,user?.username,user?.mustChangePassword]);
 useEffect(()=>{const leave=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[dirty]);
 const move=target=>{if(dirty&&!window.confirm('تغییرات ذخیره نشده است. بدون ذخیره خارج می‌شوید؟'))return;setSection(target);setEditing(null);setDirty(false);setNotice(null);setFilter('');};
 const edit=item=>{if(dirty&&!window.confirm('تغییرات ذخیره نشده کنار گذاشته شود؟'))return;setEditing(structuredClone(item));setDirty(false);setNotice(null);};
 const update=(key,value)=>{setEditing(prev=>({...prev,[key]:value}));setDirty(true);};
 const upload=async file=>{if(file.size>8*1024*1024){report(new Error('حجم تصویر نباید بیشتر از ۸ مگابایت باشد.'));return;}setUploading(true);try{const form=new FormData();form.append('file',file);const item=await request('admin/media',{method:'POST',body:form});setMedia(prev=>[item,...prev]);return item;}catch(e){report(e);}finally{setUploading(false);}};
 const login=async e=>{e.preventDefault();setBusy(true);setNotice(null);try{setUser(await request('auth/login',{method:'POST',body:credentials}));setCredentials({username:'',password:''});setSection('overview');}catch(e){report(e);}finally{setBusy(false);}};
 const logout=async()=>{if(dirty&&!window.confirm('بدون ذخیره خارج می‌شوید؟'))return;try{await request('auth/logout',{method:'POST'});setUser(null);setEditing(null);setDirty(false);setDataReady(false);}catch(e){report(e);}};
 const changePassword=async e=>{e.preventDefault();if(passwords.newPassword!==passwords.confirm){report(new Error('تکرار رمز جدید یکسان نیست.'));return;}setBusy(true);try{await request('auth/password',{method:'POST',body:{currentPassword:passwords.currentPassword,newPassword:passwords.newPassword}});setUser(null);setPasswords({currentPassword:'',newPassword:'',confirm:''});setNotice({text:'رمز تغییر کرد. با رمز جدید وارد شوید.'});}catch(e){report(e);}finally{setBusy(false);}};
 const save=async e=>{e.preventDefault();setBusy(true);setNotice(null);try{
  if(section==='content'){const saved=await request('admin/content',{method:'PUT',body:{version:content.version,data:editing}});setContent(saved);setEditing(structuredClone(saved.data));}
  else {const fields=section==='products'?Object.keys(blankProduct):section==='slides'?Object.keys(blankSlide):Object.keys(blankCategory);const body=Object.fromEntries(fields.map(k=>[k,editing[k]]));if(editing.id)body.version=editing.version;const saved=await request(`admin/${section}${editing.id?'/'+editing.id:''}`,{method:editing.id?'PUT':'POST',body});setEditing(saved);const setter=section==='products'?setProducts:section==='slides'?setSlides:setCategories;setter(prev=>{const list=prev.some(x=>x.id===saved.id)?prev.map(x=>x.id===saved.id?saved:x):[saved,...prev];return section==='slides'?list.sort((a,b)=>a.position-b.position):list;});}
  setDirty(false);setNotice({text:'تغییرات ذخیره شد.'});
 }catch(e){report(e);}finally{setBusy(false);}};
 const passwordForm=<form className="admin-form password-form" onSubmit={changePassword}><p>رمز جدید حداقل ۱۲ کاراکتر باشد. پس از تغییر، همه نشست‌ها بسته می‌شوند.</p><label className="admin-field"><span>رمز فعلی</span><input type="password" autoComplete="current-password" required value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/></label><label className="admin-field"><span>رمز جدید</span><input type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})}/></label><label className="admin-field"><span>تکرار رمز جدید</span><input type="password" autoComplete="new-password" minLength={12} required value={passwords.confirm} onChange={e=>setPasswords({...passwords,confirm:e.target.value})}/></label><button className="admin-primary" disabled={busy}>{busy?'در حال ذخیره…':'تغییر رمز'}</button></form>;
 return <div className="admin-app" dir="rtl"><a className="admin-skip" href="#admin-main">رفتن به محتوای پنل</a>{!ready?<p className="admin-loading">در حال بارگذاری…</p>:!user?<main className="admin-login" id="admin-main"><a href="/"><img src="/brand/logo-fa-gold.png" alt="جهان تجارت مجد"/></a><div className="login-card"><span className="admin-eyebrow">مدیریت جهان تجارت مجد</span><h1>خوش آمدید</h1><p>برای مدیریت محتوای سایت وارد شوید.</p>{notice&&<div className={`admin-notice ${notice.error?'error':''}`} role={notice.error?'alert':'status'}>{notice.text}</div>}<form onSubmit={login}><label className="admin-field"><span>نام کاربری</span><input autoComplete="username" dir="ltr" required maxLength={80} value={credentials.username} onChange={e=>setCredentials({...credentials,username:e.target.value})}/></label><label className="admin-field"><span>رمز عبور</span><input type="password" autoComplete="current-password" dir="ltr" required maxLength={256} value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/></label><button className="admin-primary" disabled={busy}>{busy?'در حال ورود…':'ورود به پنل'}</button></form><a className="login-back" href="/">بازگشت به سایت ←</a></div></main>:<>
 <aside className="admin-sidebar"><a className="admin-brand" href="/"><img src="/brand/logo-fa-gold.png" alt="جهان تجارت مجد"/><span>مدیریت وب‌سایت</span></a><nav aria-label="بخش‌های مدیریت">{sections.map(([key,label],i)=><button key={key} className={section===key?'active':''} disabled={user.mustChangePassword&&key!=='password'} aria-current={section===key?'page':undefined} onClick={()=>move(key)}><span className="section-number">{String(i+1).padStart(2,'0')}</span>{label}</button>)}</nav><div className="admin-sidebar-bottom"><span dir="ltr">{user.username}</span><button onClick={logout}>خروج از حساب</button></div></aside>
 <main className="admin-workspace" id="admin-main"><header className="admin-top"><div><span className="admin-eyebrow">جهان تجارت مجد</span><h1>{user.mustChangePassword?'تغییر رمز اولیه':sections.find(s=>s[0]===section)?.[1]}</h1></div><a href="/" target="_blank" rel="noreferrer">مشاهده سایت ↗</a></header>
 {notice&&<div className={`admin-notice ${notice.error?'error':''}`} role={notice.error?'alert':'status'}>{notice.text}</div>}
 {user.mustChangePassword?<><div className="admin-notice">برای فعال‌شدن پنل، رمز اولیه را تغییر دهید.</div>{passwordForm}</>:section==='password'?passwordForm:!dataReady?<div className="admin-panel"><p>در حال دریافت اطلاعات…</p>{notice?.error&&<button className="admin-primary" onClick={load}>تلاش دوباره</button>}</div>:<>
 {section==='overview'&&<><div className="admin-welcome"><div><h2>محتوای سایت، در اختیار شما</h2><p>محصول تازه اضافه کنید، اسلایدر را تغییر دهید و متن‌ها را در دو زبان به‌روز نگه دارید.</p><button className="admin-primary" onClick={()=>{move('products');edit({...blankProduct});}}>افزودن اولین محصول یا محصول جدید +</button></div><span aria-hidden="true">MGT</span></div><div className="admin-stats">{[['محصول منتشرشده',products.filter(p=>p.status==='PUBLISHED').length,'products'],['پیش‌نویس',products.filter(p=>p.status==='DRAFT').length,'products'],['اسلاید فعال',slides.filter(s=>s.active).length,'slides'],['تصاویر',media.length,'media']].map(([label,count,key])=><button key={label} onClick={()=>move(key)}><strong>{count.toLocaleString('fa-IR')}</strong><span>{label}</span></button>)}</div><div className="admin-panel"><h2>از کجا شروع کنیم؟</h2><ol className="admin-steps"><li>در بخش محصولات، نام فارسی و انگلیسی و تصاویر را وارد کنید.</li><li>تا آماده‌شدن اطلاعات، وضعیت محصول را روی پیش‌نویس نگه دارید.</li><li>با انتخاب «منتشرشده» و ذخیره، محصول در صفحه محصولات نمایش داده می‌شود.</li></ol><p className="admin-muted">تغییرات اسلایدر و متن‌ها پس از ذخیره در سایت اعمال می‌شوند.</p></div></>}
 {['products','categories','slides'].includes(section)&&<><div className="admin-toolbar"><input aria-label="جست‌وجو در موارد" placeholder="جست‌وجو در این بخش…" value={filter} onChange={e=>setFilter(e.target.value)}/><button className="admin-primary" onClick={()=>edit(structuredClone(section==='products'?blankProduct:section==='slides'?{...blankSlide,position:slides.length}:blankCategory))}>+ {section==='products'?'محصول جدید':section==='slides'?'اسلاید جدید':'دسته‌بندی جدید'}</button></div><div className={`admin-editor-layout ${editing?'has-editor':''}`}><div className="admin-items">{(section==='products'?products:section==='slides'?slides:categories).filter(x=>`${x.nameFa||x.titleFa} ${x.nameEn||x.titleEn} ${x.sku||''}`.toLowerCase().includes(filter.toLowerCase())).map(item=><button className={`admin-item ${editing?.id===item.id?'selected':''}`} key={item.id} onClick={()=>edit(item)}>{(item.image||item.images?.[0])&&<img src={item.image||item.images[0]} alt=""/>}<span><strong>{item.nameFa||item.titleFa}</strong><small dir="ltr">{item.nameEn||item.titleEn}</small></span>{section!=='categories'&&<span className={`status-pill ${item.status==='PUBLISHED'||item.active?'published':''}`}>{section==='products'?statusLabels[item.status]:item.active?'فعال':'غیرفعال'}</span>}</button>)}{!(section==='products'?products:section==='slides'?slides:categories).length&&<div className="admin-panel empty-admin">هنوز موردی اضافه نشده است.</div>}</div>
 {editing&&<form className="admin-form" onSubmit={save}><div className="editor-heading"><h2>{editing.id?'ویرایش':'افزودن'} {section==='products'?'محصول':section==='slides'?'اسلاید':'دسته‌بندی'}</h2><button type="button" className="text-button" onClick={()=>edit(null)}>بستن</button></div><fieldset disabled={busy||uploading}>
 <div className="admin-pair"><Field label="نام / عنوان فارسی" required maxLength={180} value={editing[section==='slides'?'titleFa':'nameFa']} onChange={v=>update(section==='slides'?'titleFa':'nameFa',v)}/><Field label="نام / عنوان انگلیسی" dir="ltr" required maxLength={180} value={editing[section==='slides'?'titleEn':'nameEn']} onChange={v=>update(section==='slides'?'titleEn':'nameEn',v)}/></div>
 {section!=='slides'&&<Field label="نشانی کوتاه (Slug)" required dir="ltr" maxLength={100} value={editing.slug} onChange={v=>update('slug',v)} hint="مثلاً brake-disc؛ فقط حروف انگلیسی کوچک، عدد و خط تیره."/>}
 {section==='products'&&<><div className="admin-pair"><Field label="شماره قطعه / کد محصول" dir="ltr" maxLength={100} value={editing.sku} onChange={v=>update('sku',v)}/><label className="admin-field"><span>دسته‌بندی</span><select value={editing.categoryId||''} onChange={e=>update('categoryId',e.target.value||null)}><option value="">بدون دسته‌بندی</option>{categories.map(c=><option key={c.id} value={c.id}>{c.nameFa}</option>)}</select></label></div><div className="admin-pair"><Field label="توضیحات فارسی" multiline value={editing.descriptionFa} onChange={v=>update('descriptionFa',v)}/><Field label="توضیحات انگلیسی" dir="ltr" multiline value={editing.descriptionEn} onChange={v=>update('descriptionEn',v)}/><Field label="مشخصات فارسی" multiline maxLength={8000} value={editing.specsFa} onChange={v=>update('specsFa',v)} hint="هر مشخصه در یک خط؛ مثل جنس: فولاد"/><Field label="مشخصات انگلیسی" dir="ltr" multiline maxLength={8000} value={editing.specsEn} onChange={v=>update('specsEn',v)}/></div><h3>تصاویر محصول</h3><ImagePicker images={editing.images} multiple onChange={v=>update('images',v)} media={media} onUpload={upload} busy={uploading}/><label className="admin-field"><span>وضعیت نمایش</span><select value={editing.status} onChange={e=>update('status',e.target.value)}>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><p className="field-hint">پیش‌نویس و بایگانی در سایت دیده نمی‌شوند. برای بازگرداندن مورد بایگانی‌شده، وضعیت را تغییر دهید.</p></>}
 {section==='slides'&&<><div className="admin-pair"><Field label="توضیح فارسی" multiline maxLength={1000} value={editing.captionFa} onChange={v=>update('captionFa',v)}/><Field label="توضیح انگلیسی" dir="ltr" multiline maxLength={1000} value={editing.captionEn} onChange={v=>update('captionEn',v)}/></div><h3>تصویر اسلاید</h3><ImagePicker images={editing.image?[editing.image]:[]} onChange={v=>update('image',v[0]||'')} media={media} onUpload={upload} busy={uploading}/><Field label="لینک اسلاید" dir="ltr" maxLength={200} value={editing.href} onChange={v=>update('href',v)} hint="مثلاً /products یا /products/brake-disc؛ برای نداشتن دکمه خالی بگذارید."/><Field label="ترتیب نمایش (عدد کمتر، جلوتر)" type="number" value={editing.position} onChange={v=>update('position',Number(v))}/><label className="admin-check"><input type="checkbox" checked={editing.active} onChange={e=>update('active',e.target.checked)}/>نمایش این اسلاید در سایت</label></>}
 <div className="admin-save"><button className="admin-primary" disabled={busy||uploading}>{busy?'در حال ذخیره…':section==='products'&&editing.status==='PUBLISHED'?'ذخیره و انتشار':'ذخیره تغییرات'}</button>{dirty&&<span>تغییرات ذخیره نشده</span>}{section==='products'&&editing.id&&editing.status==='PUBLISHED'&&!dirty&&<a href={`/products/${editing.slug}`} target="_blank" rel="noreferrer">مشاهده محصول ↗</a>}</div></fieldset></form>}</div></>}
 {section==='content'&&(!editing?<div className="admin-panel"><h2>متن‌های صفحه اصلی، درباره ما و اطلاعات تماس</h2><p>متن‌ها در دو زبان جداگانه ویرایش می‌شوند و قالب سایت ثابت می‌ماند.</p><button className="admin-primary" onClick={()=>edit(content.data)}>ویرایش محتوا</button></div>:<form className="admin-form" onSubmit={save}><fieldset disabled={busy}><div className="admin-pair content-languages">{['fa','en'].map(lang=><section key={lang}><h2>{lang==='fa'?'فارسی':'English'}</h2>{contentFields.map(([key,label,multi,max])=><Field key={key} label={label} value={editing[lang][key]} dir={lang==='en'?'ltr':'rtl'} multiline={multi} maxLength={max} required={key!=='contactText'} onChange={v=>update(lang,{...editing[lang],[key]:v})}/>)}</section>)}</div><h2>راه‌های ارتباطی</h2><div className="admin-pair">{[['officePhone','تلفن شرکت'],['managementPhone','تلفن مدیریت'],['companyEmail','ایمیل شرکت'],['directorEmail','ایمیل مدیریت']].map(([key,label])=><Field key={key} label={label} dir="ltr" required type={key.includes('Email')?'email':'tel'} maxLength={200} value={editing[key]} hint={key.includes('Phone')?'با کد کشور و بدون فاصله؛ مثل +982188563648':undefined} onChange={v=>update(key,v)}/>)}</div><div className="admin-save"><button className="admin-primary" disabled={busy}>{busy?'در حال ذخیره…':'ذخیره و انتشار متن‌ها'}</button>{dirty&&<span>تغییرات ذخیره نشده</span>}</div></fieldset></form>)}
 {section==='media'&&<div className="admin-panel"><h2>تصاویر سایت</h2><p className="admin-muted">تصاویر بارگذاری‌شده را هنگام ویرایش محصولات و اسلایدها انتخاب کنید.</p><ImagePicker images={[]} onChange={()=>{}} media={[]} onUpload={upload} busy={uploading}/><div className="media-grid">{media.map(m=><figure key={m.id}><img src={m.url} alt={m.name} loading="lazy"/><figcaption>{m.name}<small>{Math.ceil(m.size/1024)} KB</small></figcaption></figure>)}</div>{media.length===0&&<p>هنوز تصویری بارگذاری نشده است.</p>}</div>}
 </>}
 </main></>}
 </div>;
}
