export const fallbackContent = {
  fa: {
    dir: 'rtl', locale: 'fa', switchLabel: 'En', title: 'جهان تجارت مجد | واردات قطعات خودرو',
    skip: 'رفتن به محتوای اصلی', brandLabel: 'جهان تجارت مجد، صفحه اصلی',
    nav: ['صفحه اصلی', 'محصولات', 'درباره ما', 'تماس با ما'], searchPlaceholder: 'جست‌وجوی محصولات...', searchLabel: 'جست‌وجوی محصولات',
    searchEmpty: 'نام یا دسته محصول را وارد کنید.', searchMiss: 'محصولی با این عبارت پیدا نشد.',
    slides: [
      { title: 'قطعات موتور', caption: 'واردات و تأمین قطعات موتور خودرو', keys: 'موتور پیشرانه فیلتر engine parts' },
      { title: 'سیستم ترمز', caption: 'راهکارهای مطمئن برای مجموعه‌های ترمز خودرو', keys: 'ترمز دیسک لنت brake system' },
      { title: 'تعلیق و فرمان', caption: 'قطعات سیستم تعلیق، جلوبندی و فرمان', keys: 'تعلیق فرمان جلوبندی suspension steering' },
      { title: 'قطعات الکتریکی', caption: 'تأمین مجموعه‌های برقی و الکترونیکی خودرو', keys: 'برق الکتریکی باتری چراغ electrical parts' },
    ],
    previousSlide: 'اسلاید قبلی', nextSlide: 'اسلاید بعدی', goToSlide: 'رفتن به اسلاید',
    aboutLabel: 'درباره ما', aboutTitle: 'تجارت،\nبا نگاهی فراتر.',
    belief: 'در جهان تجارت مجد، ما فراتر از تجارت، به ساختن روابطی پایدار و ارزش‌آفرین باور داریم.',
    directorLabel: 'پیام مدیرعامل', directorMessage: 'به عنوان مدیر عامل، هر روز با اشتیاق و تعهد در کنار تیم‌مان تلاش می‌کنیم تا نه‌تنها نیازهای تجاری شما را برآورده کنیم، بلکه با هم مسیر موفقیت و پیشرفت را بسازیم.',
    contactLabel: 'تماس با ما', contactTitle: 'ارتباط با شرکت', contactText: 'برای گفتگو درباره همکاری یا دریافت اطلاعات بیشتر، از راه‌های زیر با ما در تماس باشید.',
    addressLabel: 'آدرس', address: 'تهران، بلوار دریا، ابتدای پاکنژاد، کوچه عیسی‌پور، پلاک ۲۸، واحد ۱',
    officePhone: 'تلفن شرکت', managementPhone: 'تلفن مدیریت', companyEmail: 'ایمیل شرکت', directorEmail: 'ایمیل مدیریت', call: 'تماس', copy: 'کپی', copied: 'کپی شد', copyFailed: 'کپی انجام نشد', companyGroup: 'ارتباط با شرکت', managementGroup: 'ارتباط با مدیریت',
    footerCompany: 'جهان تجارت مجد', footerNavLabel: 'دسترسی‌های پایین صفحه', backTop: 'بازگشت به بالا',
  },
  en: {
    dir: 'ltr', locale: 'en', switchLabel: 'Fa', title: 'Majd Global Trading | Automotive Parts Importer',
    skip: 'Skip to main content', brandLabel: 'Majd Global Trading, home',
    nav: ['Home', 'Products', 'About us', 'Contact us'], searchPlaceholder: 'Search products...', searchLabel: 'Search products',
    searchEmpty: 'Enter a product name or category.', searchMiss: 'No matching product was found.',
    slides: [
      { title: 'Engine Parts', caption: 'Import and supply of automotive engine components', keys: 'engine motor filters قطعات موتور' },
      { title: 'Braking System', caption: 'Reliable solutions for automotive braking systems', keys: 'brake disc pad ترمز لنت' },
      { title: 'Suspension & Steering', caption: 'Suspension, chassis and steering components', keys: 'suspension steering تعلیق فرمان جلوبندی' },
      { title: 'Electrical Parts', caption: 'Automotive electrical and electronic components', keys: 'electrical battery light قطعات برقی الکتریکی' },
    ],
    previousSlide: 'Previous slide', nextSlide: 'Next slide', goToSlide: 'Go to slide',
    aboutLabel: 'About us', aboutTitle: 'Trade,\nwith a broader vision.',
    belief: 'At Jahan Tejarat Majd, we believe in building enduring and value-creating relationships, beyond just trade.',
    directorLabel: "Managing Director's message", directorMessage: 'As the Managing Director, every day, with passion and commitment, we strive alongside our team not only to meet your business needs but to jointly shape a path of success and progress.',
    contactLabel: 'Contact us', contactTitle: 'Contact the company', contactText: 'To discuss a partnership or request more information, please contact us using the details below.',
    addressLabel: 'Address', address: 'Tehran, Iran',
    officePhone: 'Office phone', managementPhone: 'Management', companyEmail: 'Company email', directorEmail: 'Management email', call: 'Call', copy: 'Copy', copied: 'Copied', copyFailed: 'Could not copy', companyGroup: 'Company enquiries', managementGroup: 'Management enquiries',
    footerCompany: 'MAJD GLOBAL TRADING', footerNavLabel: 'Footer navigation', backTop: 'Back to top',
  },
};
