'use client';
import { useEffect,useState } from 'react';
import { useSearchParams,useRouter } from 'next/navigation';
import { useSite } from '../../components/site-provider';
import { CatalogShell } from '../../components/site-shell';
export default function ProductList(){
 const {isEnglish}=useSite();const params=useSearchParams();const router=useRouter();
 const q=params.get('q')||'',category=params.get('category')||'',page=Number(params.get('page')||1);
 const [data,setData]=useState(null),[categories,setCategories]=useState([]),[error,setError]=useState(false);
 useEffect(()=>{fetch('/api/public/categories').then(r=>r.ok?r.json():[]).then(setCategories).catch(()=>{});},[]);
 useEffect(()=>{let active=true;setData(null);setError(false);fetch(`/api/public/products?${new URLSearchParams({q,category,page:String(page)})}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(active)setData(d);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[q,category,page]);
 const navigate=(values)=>{const next=new URLSearchParams({q,category,...values});for(const [k,v] of [...next])if(!v)next.delete(k);router.push(`/products?${next}`);};
 const name=p=>p[isEnglish?'nameEn':'nameFa'];
 return <CatalogShell><div className="shell catalog-content"><div className="catalog-heading"><span className="section-kicker">MGT / {isEnglish?'CATALOGUE':'کاتالوگ'}</span><h1>{isEnglish?'Our products':'محصولات ما'}</h1><p>{isEnglish?'Browse our automotive parts and contact us for specifications and supply enquiries.':'قطعات خودرو را مرور کنید و برای مشخصات و شرایط تأمین با ما در تماس باشید.'}</p></div>
 <form className="catalog-filters" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);navigate({q:f.get('q').trim(),category:f.get('category'),page:'1'});}} key={`${q}/${category}`}><label>{isEnglish?'Search':'جست‌وجو'}<input name="q" defaultValue={q} maxLength={150} placeholder={isEnglish?'Name or part number':'نام یا شماره قطعه'}/></label><label>{isEnglish?'Category':'دسته‌بندی'}<select name="category" defaultValue={category}><option value="">{isEnglish?'All categories':'همه دسته‌ها'}</option>{categories.map(c=><option key={c.id} value={c.slug}>{name(c)}</option>)}</select></label><button className="gold-button">{isEnglish?'Find products':'نمایش محصولات'}</button></form>
 {error?<div className="catalog-empty" role="alert">{isEnglish?'Products could not be loaded. Please refresh the page.':'دریافت محصولات انجام نشد؛ صفحه را دوباره بارگذاری کنید.'}</div>:!data?<p role="status">{isEnglish?'Loading products…':'در حال دریافت محصولات…'}</p>:data.items.length===0?<div className="catalog-empty"><h2>{q||category?(isEnglish?'No matching products':'محصولی پیدا نشد'):(isEnglish?'Our catalogue is being prepared':'کاتالوگ محصولات در حال تکمیل است')}</h2><p>{isEnglish?'Contact us to discuss the parts you need.':'برای اطلاع از تأمین قطعات موردنیازتان با ما در تماس باشید.'}</p><a className="gold-button" href="/#contact">{isEnglish?'Contact us':'تماس با ما'}</a></div>:<><p className="result-count">{data.total} {isEnglish?'products':'محصول'}</p><div className="product-grid">{data.items.map(p=><a className="product-card" key={p.id} href={`/products/${p.slug}`}><div className="product-image">{p.images[0]&&<img loading="lazy" src={p.images[0]} alt={name(p)}/>}</div><div className="product-card-copy"><span>{p.category?name(p.category):'MGT'}</span><h2>{name(p)}</h2>{p.sku&&<p dir="ltr">{p.sku}</p>}<span className="product-more">{isEnglish?'View details →':'مشاهده مشخصات ←'}</span></div></a>)}</div>{data.pages>1&&<nav className="pagination" aria-label={isEnglish?'Pagination':'صفحه‌بندی'}><button disabled={page<=1} onClick={()=>navigate({page:String(page-1)})}>{isEnglish?'Previous':'قبلی'}</button><span>{page} / {data.pages}</span><button disabled={page>=data.pages} onClick={()=>navigate({page:String(page+1)})}>{isEnglish?'Next':'بعدی'}</button></nav>}</>}
 </div></CatalogShell>;
}
